apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-cloud-infra-demo

resources:
  - ../base/namespace.yaml
  - ../base

# Production uses base configuration
# Can add production-specific patches here if needed

